# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setup MATLAB on Runner
        uses: matlab-actions/setup-matlab@v1

      # Runs a set of commands using the runners shell
      - name: Run MATLAB tests
        uses: matlab-actions/run-tests@v1
        with:
          source-folder: xlim-ops-matlab/src
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: coverage.xml
        
        # with:
          # test-results-junit: test-results/results.xml
          # code-coverage-cobertura: code-coverage/coverage.xml
          
      - uses: codecov/codecov-action@v1
        with:
          file: coverage.xml
          
      - name: Upload results artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          # name: test-restults
          # path: test-results/results.xml

          name: code-coverage
          path: coverage.xml
